title: "de gustibus."
description: "Ici je parle un peu d'art"
url: "https://degustibus.fr"
baseurl: ""
lang: "fr"
timezone: "Europe/Paris"
markdown: kramdown
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      tags: []
      image: ""

plugins:
  - jekyll-sitemap
