title: "de gustibus."
description: "Ici je parle un peu d'art"
url: "https://degustibus.fr"
baseurl: ""
lang: "fr"
timezone: "Europe/Paris"
markdown: kramdown
permalink: /:title/

collections:
  photos:
    output: true
    permalink: /photos/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      tags: []
      image: ""

  - scope:
      path: ""
      type: photos
    values:
      layout: photo
      image: ""
      title: ""
      date: ""
      location: ""
      caption: ""

plugins:
  - jekyll-sitemap
