author: ""
bio: ""
logo_text: "de gustibus."
quote: "Il y a dans l’art un point de perfection comme de bonté ou de maturité dans la nature : celui qui le sent et qui l’aime a le goût parfait, celui qui ne le sent pas et qui aime en deçà et au delà a le goût défectueux. Il y a donc un bon et un mauvais goût, et l’on dispute des goûts avec fondement"
